# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "backup" ]
  pull_request:
    branches: [ "backup" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: create env file
      run: |
        touch .env
        echo PORT=$PORT >> .env
        echo MONGODB_URL=$MONGODB_URL >> .env
        echo FIREBASE_TYPE=$FIREBASE_TYPE >> .env
        echo FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID >> .env
        echo FIREBASE_PRIVATE_KEY_ID=$FIREBASE_PRIVATE_KEY_ID >> .env
        echo FIREBASE_PRIVATE_KEY=$FIREBASE_PRIVATE_KEY >> .env
        echo FIREBASE_CLIENT_EMAIL=$FIREBASE_CLIENT_EMAIL >> .env
        echo FIREBASE_CLIENT_ID=$FIREBASE_CLIENT_ID >> .env
        echo FIREBASE_AUTH_URI=$FIREBASE_AUTH_URI >> .env
        echo FIREBASE_TOKEN_URI=$FIREBASE_TOKEN_URI >> .env
        echo FIREBASE_AUTH_PROVIDER_X509_CERT_URL=$FIREBASE_AUTH_PROVIDER_X509_CERT_URL >> .env
        echo FIREBASE_CLIENT_X509_CERT_URL=$FIREBASE_CLIENT_X509_CERT_URL >> .env
        echo ADOPTPET_FIREBASE_TYPE=$ADOPTPET_FIREBASE_TYPE >> .env
        echo ADOPTPET_FIREBASE_PROJECT_ID=$ADOPTPET_FIREBASE_PROJECT_ID >> .env
        echo ADOPTPET_FIREBASE_PRIVATE_KEY_ID=$ADOPTPET_FIREBASE_PRIVATE_KEY_ID >> .env
        echo ADOPTPET_FIREBASE_PRIVATE_KEY=$ADOPTPET_FIREBASE_PRIVATE_KEY >> .env
        echo ADOPTPET_FIREBASE_CLIENT_EMAIL=$ADOPTPET_FIREBASE_CLIENT_EMAIL >> .env
        echo ADOPTPET_FIREBASE_CLIENT_ID=$ADOPTPET_FIREBASE_CLIENT_ID >> .env
        echo ADOPTPET_FIREBASE_AUTH_URI=$ADOPTPET_FIREBASE_AUTH_URI >> .env
        echo ADOPTPET_FIREBASE_TOKEN_URI=$ADOPTPET_FIREBASE_TOKEN_URI >> .env
        echo ADOPTPET_FIREBASE_AUTH_PROVIDER_X509_CERT_URL=$ADOPTPET_FIREBASE_AUTH_PROVIDER_X509_CERT_URL >> .env
        echo ADOPTPET_FIREBASE_CLIENT_X509_CERT_URL=$ADOPTPET_FIREBASE_CLIENT_X509_CERT_URL >> .env
        echo BABYCARE_FIREBASE_TYPE=$BABYCARE_FIREBASE_TYPE >> .env
        echo BABYCARE_FIREBASE_PROJECT_ID=$BABYCARE_FIREBASE_PROJECT_ID >> .env
        echo BABYCARE_FIREBASE_PRIVATE_KEY_ID=$BABYCARE_FIREBASE_PRIVATE_KEY_ID >> .env
        echo BABYCARE_FIREBASE_PRIVATE_KEY=$BABYCARE_FIREBASE_PRIVATE_KEY >> .env
        echo BABYCARE_FIREBASE_CLIENT_EMAIL=$BABYCARE_FIREBASE_CLIENT_EMAIL >> .env
        echo BABYCARE_FIREBASE_CLIENT_ID=$BABYCARE_FIREBASE_CLIENT_ID >> .env
        echo BABYCARE_FIREBASE_AUTH_URI=$BABYCARE_FIREBASE_AUTH_URI >> .env
        echo BABYCARE_FIREBASE_TOKEN_URI=$BABYCARE_FIREBASE_TOKEN_URI >> .env
        echo BABYCARE_FIREBASE_AUTH_PROVIDER_X509_CERT_URL=$BABYCARE_FIREBASE_AUTH_PROVIDER_X509_CERT_URL >> .env
        echo BABYCARE_FIREBASE_CLIENT_X509_CERT_URL=$BABYCARE_FIREBASE_CLIENT_X509_CERT_URL >> .env
    - run: yarn install
    - run: node dists/init.js

